name: dl-workshop
channels:
  - anaconda
  - conda-forge
  - pytorch
dependencies:
- python=3.6.4
- numpy=1.14.0
- scipy=1.0.0
- pandas=0.22.0
- matplotlib=2.1.2
- seaborn=0.8.1
- scikit-learn=0.19.1
- ipython=6.2.1
- notebook=5.5.0
- jupyterlab=0.32.1
- pytorch-cpu=0.4.0
- opencv=3.3.1
- pillow=5.1.0
- pip:
  - torchvision==0.2.1
